export const productList = [
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbG6YRyrslUbxGP4OCf4qJ4GNMIGxRgsB8QnUVmSRGOeIgCfxswf9N3o6eOUpXpXbog2A&usqp=CAU",
    name: "Spicy seasoned seafood noodles",
    price: "1.00",
    qnt: "5",
    id: "1",
    count: "0",
  },
  {
    img: "https://pngimg.com/uploads/soup/small/soup_PNG80.png",
    name: "Salted Pasta with mushroom sauce",
    price: "2.00",
    qnt: "9",
    id: "2",
    count: "0",
  },
  {
    img: "https://mediavine-res.cloudinary.com/image/upload/s--3MFAevEx--/c_limit,f_auto,fl_lossy,h_1080,q_auto,w_1920/v1695938019/x0ztmihl7hmfz0hpyny3.jpg",
    name: "Beef dumpling in hot and sour soup",
    price: "214.00",
    qnt: "8",
    id: "3",
    count: "0",
  },
  {
    img: "https://assets.bonappetit.com/photos/57acc781f1c801a1038bc76a/1:1/w_320,c_limit/twice-roasted-sweet-potatoes-with-hot-honey.jpg",
    name: "Healthy noodle with spinach leaf",
    price: "200.00",
    qnt: "8",
    id: "4",
    count: "0",
  },
  {
    img: "https://images.immediate.co.uk/production/volatile/sites/30/2022/09/Root-Veg-Hot-Pot-ce1d4b0.jpg?quality=90&resize=556,505",
    name: "Hot spicy fried rice with omelet",
    price: "525.00",
    qnt: "1",
    id: "5",
    count: "0",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQl1XaAAhn7gTcmS_-D8E_ka5YzQmmHZIpSC25tQ9zZM7UUYSNx1uT8N4SD1a4GikKa0_k&usqp=CAU",
    name: "Spicy instant noodle with special omelette",
    price: "585.00",
    qnt: "9",
    id: "6",
    count: "0",
  },
  {
    img: "https://christieathome.com/wp-content/uploads/2023/10/Hot-and-Sour-Soup14.jpg",
    name: "Refined Frozen Tuna",
    price: "472.00",
    qnt: "5",
    id: "7",
    count: "0",
  },
  {
    img: "https://redhousespice.com/wp-content/uploads/2021/08/Chinese-hot-and-sour-soup-1-scaled.jpg",
    name: "Awesome Plastic Computer",
    price: "953.00",
    qnt: "2",
    id: "8",
    count: "0",
  },
  {
    img: "https://bigoven-res.cloudinary.com/image/upload/t_recipe-1280/cantonese-style-hot-and-sour-s-e7c747.jpg",
    name: "Recycled Rubber Chicken",
    price: "733.00",
    qnt: "3",
    id: "9",
    count: "0",
  },
  {
    img: "https://www.krumpli.co.uk/wp-content/uploads/2024/02/Chinese-Hot-and-Sour-Soup-6-Pin-150x150.jpg",
    name: "Small Cotton Computer",
    price: "344.00",
    qnt: "5",
    id: "10",
    count: "0",
  },
  {
    img: "https://redhousespice.com/wp-content/uploads/2021/08/Chinese-hot-and-sour-soup-1-scaled.jpg",
    name: "Intelligent Bronze Shirt",
    price: "688.00",
    qnt: "5",
    id: "11",
    count: "0",
  },
  {
    img: "https://lh3.googleusercontent.com/pw/ABLVV85PCTQYtSY5GhLNK_emdyVQmH1gexZPO0C7VwbcsYDEzR_sytzLUjQCYQj9J79iDTz_cNxvW0YyMdZREbaAYlgWdOWcLNDKcVcZxy-JnuAbEG8N0d3y_CijkXEgXrL1VpNjIJIqNJ0E4uLCffGCSoKg1w=w500-h500-no-gm?authuser=2",
    name: "Recycled Plastic Chips",
    price: "500.00",
    qnt: "8",
    id: "12",
    count: "0",
  },
  {
    img: "https://i.pinimg.com/736x/79/17/09/791709f3d85457c36ecc30d44c332e60.jpg ",
    name: "Incredible Steel Car",
    price: "149.00",
    qnt: "7",
    id: "13",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Fantastic Metal Chair",
    price: "347.00",
    qnt: "9",
    id: "14",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Rustic Granite Cheese",
    price: "785.00",
    qnt: "7",
    id: "15",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Handcrafted Granite Ball",
    price: "392.00",
    qnt: "7",
    id: "16",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Elegant Concrete Bike",
    price: "117.00",
    qnt: "6",
    id: "17",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Gorgeous Steel Sausages",
    price: "236.00",
    qnt: "8",
    id: "18",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Gorgeous Wooden Fish",
    price: "34.00",
    qnt: "3",
    id: "19",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Fantastic Rubber Shirt",
    price: "637.00",
    qnt: "3",
    id: "20",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Tasty Soft Shoes",
    price: "87.00",
    qnt: "8",
    id: "21",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Recycled Granite Hat",
    price: "833.00",
    qnt: "2",
    id: "22",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Handmade Granite Car",
    price: "567.00",
    qnt: "9",
    id: "23",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Handcrafted Granite Sausages",
    price: "301.00",
    qnt: "5",
    id: "24",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Rustic Steel Bike",
    price: "950.00",
    qnt: "3",
    id: "25",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Intelligent Frozen Tuna",
    price: "476.00",
    qnt: "2",
    id: "26",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Generic Wooden Sausages",
    price: "35.00",
    qnt: "8",
    id: "27",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Bespoke Cotton Chicken",
    price: "297.00",
    qnt: "2",
    id: "28",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Modern Metal Tuna",
    price: "99.00",
    qnt: "5",
    id: "29",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Refined Wooden Shoes",
    price: "189.00",
    qnt: "4",
    id: "30",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Tasty Fresh Car",
    price: "38.00",
    qnt: "5",
    id: "31",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Fantastic Soft Chips",
    price: "290.00",
    qnt: "2",
    id: "32",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Practical Concrete Towels",
    price: "954.00",
    qnt: "6",
    id: "33",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Ergonomic Concrete Pants",
    price: "28.00",
    qnt: "8",
    id: "34",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Generic Fresh Gloves",
    price: "723.00",
    qnt: "6",
    id: "35",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Practical Granite Table",
    price: "433.00",
    qnt: "4",
    id: "36",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Unbranded Steel Soap",
    price: "68.00",
    qnt: "6",
    id: "37",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Practical Fresh Pizza",
    price: "104.00",
    qnt: "4",
    id: "38",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Sleek Granite Chicken",
    price: "969.00",
    qnt: "7",
    id: "39",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Oriental Concrete Cheese",
    price: "807.00",
    qnt: "6",
    id: "40",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Refined Concrete Soap",
    price: "337.00",
    qnt: "8",
    id: "41",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Oriental Fresh Chair",
    price: "997.00",
    qnt: "5",
    id: "42",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Practical Granite Towels",
    price: "291.00",
    qnt: "5",
    id: "43",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Generic Soft Hat",
    price: "284.00",
    qnt: "7",
    id: "44",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Modern Frozen Pizza",
    price: "64.00",
    qnt: "2",
    id: "45",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Fantastic Metal Tuna",
    price: "794.00",
    qnt: "9",
    id: "46",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Small Soft Computer",
    price: "861.00",
    qnt: "2",
    id: "47",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Electronic Metal Shirt",
    price: "321.00",
    qnt: "9",
    id: "48",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Tasty Fresh Chicken",
    price: "266.00",
    qnt: "6",
    id: "49",
    count: "0",
  },
  {
    img: "https://loremflickr.com/640/480/food",
    name: "Elegant Soft Soap",
    price: "702.00",
    qnt: "8",
    id: "50",
    count: "0",
  },
];
